[package]
name = "closure-pass"
version = "0.1.0"
authors = ["Kitsu <mail@kitsu.me>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.18", features = ["full"] }
quote = "1.0.4"
